export const Strings = {
    ENTER_VALID_PHONE_NUMBER: "Invalid number. Please try again.",
    INVALID_OTP: "Incorrect code. Please try again.",
    INVALID_AGE: "You must be 18 years\nold to use Vove.",
    NETWORK_ISSUE: "Network Connection issues\nPlease try again",
    SEARCH_LOCATION: "Search locations",
    ENABLE_LOCATION_SERVICE: "Please enable location service.",
    PROFILE_PAUSE: "Your Profile is paused\n\nTo discover new people\nunpause Profile",
    UPDATE_SEARCH: "It seems you’ve reached\nthe end of your matches.\n\nNew members are joining\neveryday, check back\nlater or try broadening\nyour search.",
    ENTER_STAY: "Enter your stay details and\nfind people!",
    NETWORK_CONNECTION: "Network connection down.\n\nPlease check your data connection and try again.",
    ADD_LOCATION: "Add a Stay Location",
    NO_LONGER: "You will no longer show up in\n",
    NO_LOCATION: "No Stay Locations",
    STAY_LIMIT: "You have filled up your 3 Stay limit.",
    STAY_LIMIT1: "\n\nWith Vove Xpress you can make\nuse of 8 Stay Locations\nand enjoy Unlimited Likes!",
    FILLED_UP_STAYS: "You have filled up your\n8 Stay locations.",
    DELETE_STAYS: "Try deleting unused Stays or\nediting their locations.",
    THEY_DID: "Let us know what they did.",
    OUT_OF_LIKES: "You've run out of Likes\n for the day. \n \n Upgrade to Vove Xpress to enjoy unlimited Likes.",
    UPGRADE_IOS: `Recurring billing, Cancel anytime.`,
    UPGRADE_IOS2: `\nWhen purchasing a subscription, your payment will be charged to your iTunes account, and your subscription will automatically renew for the same duration at the same price until you cancel in settings in the iTunes store at least 24 hours prior to the end of the current period. By tapping "Get Vove Xpress", you agree to our `,
    UPGRADE_ANDROID: `Recurring billing, Cancel anytime.`,
    UPGRADE_ANDROID2: `\nWhen purchasing a subscription, your payment will be charged to your Google Play account, and your subscription will automatically renew for the same duration at the same price until you cancel in settings in the Google Play store. By tapping "Get Vove Xpress", you agree to our `,
    LIMIT_CHARACTERS: `Limit 120 Characters`,
    NO_MESSAGES: `You have no messages.\n\nSearch for people\nto chat to!`,
    MESSAGE: 'Message...',
    MESSAGE_NOT_SENT: 'Message not Sent',
    DISCONNECT: 'Are you sure you want to\ndisconnect this Member?',
    LOGOUT: "Are you sure you want\nto Log Out?",
    DELETEACCOUNT: "Are you sure you want to\ndelete our account?",
    DELETESUBTEXT_1: 'If you delete your account, you\nwill lose your profile, chats and\nstay locations permanently.',
    DELETESUBTEXT_2: "An alternative is to keep your\naccount but have it hidden\nfrom searches by pausing\nyour profile.",
    DELETESUBTEXT_3: "Are you sure you want to delete\nyour account?",
    PAUSEPROILE: "You can keep your account\nbut have it not show up in\nsearches by pausing\nyour profile instead.\nYou can always unpause\nyour profile in the Settings"

}