export const APP_OPTION_MENU = "APP_OPTION_MENU";
export const APP_REPORT_MODAL = "APP_REPORT_MODAL";
export const APP_REPORTED_MODAL = "APP_REPORTED_MODAL";
export const APP_UPGRADE_MODAL = "APP_UPGRADE_MODAL";
export const APP_STAYS_UPGRADE_MODAL = "APP_STAYS_UPGRADE_MODAL";
export const APP_REPORT_KEYS = "APP_REPORT_KEYS";
export const APP_CHARACTERS_MODAL = "APP_CHARACTERS_MODAL";