export const ON_CHATLIST_ITEM_CLICKED = "ON_CHATLIST_ITEM_CLICKED";
export const ON_LISTEN_CHAT_SCREEN = "ON_LISTEN_CHAT_SCREEN";
export const ON_GET_CONVERSION = "ON_GET_CONVERSION";
export const IS_RETRY = "IS_RETRY";
export const IS_RETRY_FROM = "IS_RETRY_FROM";