export const UPDATE_USER_STAYS = "UPDATE_USER_STAYS";
export const ADD_STAYS = "ADD_STAYS";
export const SELECTED_STAYS = "SELECTED_STAYS";
export const CURRENT_MEMBER = "CURRENT_MEMBER";
export const CONNECT_USER_RESPONSE = "CONNECT_USER_RESPONSE";
export const IS_MEMBER_CHANGED = "IS_MEMBER_CHANGED";
export const CURRENT_MEMBER_IMAGE = "CURRENT_MEMBER_IMAGE";
export const IS_DELETE_MODAL_VISIBLE = "IS_DELETE_MODAL_VISIBLE";